name: Build and publish

on:
  push:
    branches:
    - "main" # Running this workflow only for develop branch

jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0 # Checking out the repo

    - name: Build and publish "head" Docker image
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: lab-icinga-summit-workshop # Provide Docker image name
        image-tag: main # Provide Docker image tag
